#!/usr/bin/env ruby
# frozen_string_literal: true

# Prevent commits on default branch (master/main)
branch = `git rev-parse --abbrev-ref HEAD`.strip
if %w[master main].include?(branch)
  $stderr.puts "Commits on '#{branch}' are not allowed. Create a feature branch."
  exit 1
end

require 'english'
require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changed_files = `git status --porcelain`.split(/\n/)
                                        .select do |file_name_with_status|
                                          file_name_with_status =~ ADDED_OR_MODIFIED
                                        end
                                        .map do |file_name_with_status|
                                          file_name_with_status.split(' ')[1]
                                        end
                                        .select do |file_name|
                                          File.extname(file_name) == '.rb'
                                        end.join(' ')

system("rubocop #{changed_files}") unless changed_files.empty?

exit $CHILD_STATUS.to_s[-1].to_i
